spring:
  profiles:
    active: dev
  application:
    name: flight-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/flight_service_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:PunePune2026}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8081
springdoc:
  swagger-ui:
    path: /swagger