server:
  port: 8888
spring:
  application:
    name: config-service
  profiles:
    active: git,vault
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/laxminarayan/airline-seat-reservation-system-config
          search-paths: configs/*
          order: 2
        vault:
          host: 127.0.0.1
          port: 8200
          scheme: http
          kv-version: 2
          order: 1